micronaut:
  application:
    name: helloGrpcRest
  server:
    port: ${APP_PORT:8788}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
      hello:
        address: 'localhost:50051'
        plaintext: true
        max-retry-attempts: 5